apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: ecommerce-backend
  namespace: ecommerce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ecommerce-backend
  template:
    metadata:
      labels:
        app: ecommerce-backend
    spec:
      containers:
        - name: ecommerce-backend
          image: phanphan1504/ecommerce-backend:85158cb85db212be9e47b3d56070b3f0386fcae5
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://postgres:5432/E_Commerence_DB"
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: ecommerce-secrets
                  key: postgres-user
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ecommerce-secrets
                  key: postgres-password
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: ecommerce-secrets
                  key: jwt-secret
            - name: ADMIN_EMAIL
              valueFrom:
                secretKeyRef:
                  name: ecommerce-secrets
                  key: admin-email
            - name: ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ecommerce-secrets
                  key: admin-password
            - name: ALLOWED_ORIGINS
              value: "http://localhost:3000,http://localhost:30080,http://vshop.local"
  strategy:
    blueGreen: 
      activeService: ecommerce-backend-active
      previewService: ecommerce-backend-preview
      autoPromotionEnabled: true
