apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: ecommerce-backend
  namespace: ecommerce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ecommerce-backend
  template:
    metadata:
      labels:
        app: ecommerce-backend
    spec:
      containers:
        - name: ecommerce-backend
          image: phanphan1504/ecommerce-backend:latest
          ports:
            - containerPort: 8080
          env:
            # ✅ FIX DỨT ĐIỂM: Truyền thẳng URL đầy đủ, không ghép biến trong code
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://postgres:5432/E_Commerence_DB"
            - name: SPRING_DATASOURCE_USERNAME
              value: "postgres"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "postgres"
            - name: ALLOWED_ORIGINS
              value: "http://localhost:3000,http://localhost:30080,http://vshop.local"
            - name: JWT_SECRET
              value: "VDB6clpTMU1YMDFPTTBaUFVVUkpSVUZVUWtkVFJWSlVWRUZVUlZKVVZFMA=="
  strategy:
    blueGreen: 
      activeService: ecommerce-backend-active
      previewService: ecommerce-backend-preview
      autoPromotionEnabled: true
