apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ecommerce-monolith
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/davidmoi2135/End-to-End-Monolithic-Deployment.git
    targetRevision: HEAD
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: ecommerce
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
